version: '3'
services:
  kf2-server:
    build: .
    ports:
      - "20560:20560/udp"
      - "27015:27015/udp"
      - "7777:7777/udp"
      - "8080:8080/tcp"
    volumes:
      - ./Cache:/home/steam/Steam/steamapps/common/killingfloor2/KFGame/Cache
      - ./Config:/home/steam/Steam/steamapps/common/killingfloor2/KFGame/Config
    # networks: 
    #   - reverse-proxy
    #   - back
    # environment:
    #   - VIRTUAL_HOST=
    #   - VIRTUAL_PORT=8080
    command: sh -c '/home/steam/Steam/steamcmd.sh +login anonymous +app_update 232130 +exit; /home/steam/Steam/steamapps/common/killingfloor2/Binaries/Win64/KFGameSteamServer.bin.x86_64 kf-bioticslab'
# networks:
#   reverse-proxy:
#     external:
#       name: reverse-proxy
#   back:
#     driver: bridge